version: '3.4'

services:
  # rabbit mq
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    image: rabbitmq:3-management

  # client service
  clientsservice:
    image: ${DOCKER_REGISTRY-}clientsservice
    container_name: "ClientsService"
    ports:
      - 5030:80
    build:
      context: .
      dockerfile: ClientsService/Dockerfile
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "ClientDB"
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "66n@DubzF"
      ACCEPT_EULA: "Y"

  # product service
  productsservice:
    image: ${DOCKER_REGISTRY-}productsservice
    container_name: "ProductsService"
    ports:
      - 5031:80
    build:
      context: .
      dockerfile: ProductsService/Dockerfile
  product_db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "ProductDB"
    ports:
      - 1434:1433
    environment:
      SA_PASSWORD: "5P83Czns!"
      ACCEPT_EULA: "Y"

  # renting service
  rentingservice:
    image: ${DOCKER_REGISTRY-}rentingservice
    container_name: "RentingService"
    ports:
      - 5032:80
    build:
      context: .
      dockerfile: RentingService/Dockerfile
  renting_db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "RentingDB"
    ports:
      - 1435:1433
    environment:
      SA_PASSWORD: "!k9uXi3ha"
      ACCEPT_EULA: "Y"
