version: '3.4'

services:
  productsservice:
    image: ${DOCKER_REGISTRY-}productsservice
    container_name: "ProductsService"
    ports:
      - 4224:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    container_name: "ProductDB"
    volumes:
      - product-db-mssql:/var/opt/mssql/data
    environment:
        SA_PASSWORD: "5P83Czns!"
        ACCEPT_EULA: "Y"
    ports:
      - 1434:1433
volumes:
   product-db-mssql: {}