apiVersion: v1
kind: Service
metadata:
    name: "puzzlerbk8s-6a80"
    labels:
        app: "puzzlerbk8s-6a80"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "puzzlerbk8s-6a80"