apiVersion: v1
kind: Service
metadata:
  name: clientsnpservice-srv
spec:
  type: NodePort
  selector:
    app: clientsservice
  ports:
  - name: clientsservice
    protocol: TCP
    port: 80
    targetPort: 80
