apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients-depl
spec:
 # k8s will ensure there is at least one replica running (if deleted, it will replicate)
  replicas: 1
 # selecting the template
  selector:
    matchLabels:
      app: clientsservice
 # Pod/container template to be used
  template:
    metadata:
      labels:
        app: clientsservice
    spec:
      containers:
      - name: clientsservice
        image: eanomaly/clientsservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
